INSERT INTO TECHNOLOGIES (technology) VALUES('Java');
INSERT INTO TECHNOLOGIES (technology) VALUES('dot.Net');
INSERT INTO TECHNOLOGIES (technology) VALUES('HTML');
INSERT INTO TECHNOLOGIES (technology) VALUES('Definicao de processos');
INSERT INTO TECHNOLOGIES (technology) VALUES('Siebel');
INSERT INTO TECHNOLOGIES (technology) VALUES('Oracle');
INSERT INTO TECHNOLOGIES (technology) VALUES('SharePoint');